Update translations.php
miraheze/landing pull request #41
Opened 2020-09-18 18:47 UTC by ahmsaqib

**Bengali translation completed**

  Name of the language - Bengali

**Code** - bn
**Area** - Bangladesh / India
**Translator** - [A H M Saqib](https://ahmsaqib.com)
**Miraheze Username** - [ahmsaqib](https://meta.miraheze.org/wiki/User:Ahmsaqib)

2020-09-18 19:40 UTC, RhinosF1 requested changes
Needs adding to language list

2020-09-19 08:35 UTC, RhinosF1 approved these changes
Lang list done in another PR, bar the minor style issue I've mentioned on that PR. Good to go.

2020-09-19 14:37 UTC, RhinosF1 approved these changes
Along with #42

2020-09-21 20:49 UTC, RhinosF1 commented
Please rebase

2020-09-24 12:42 UTC, ahmsaqib commented
check both pulls now!

2020-11-27 19:38 UTC, Aftabuzzaman commented
@ahmsaqib আমি না খেয়াল করেই, https://github.com/miraheze/landing/pull/48 অনুবাদ করে জমা দিয়েছি। অনুগ্রহ করে অনুবাদ মিলিয়ে নিয়ে সংশোধন করুন (দুই অনুবাদের জন্য যেটি বেশি ভালো লাগে সেটি ব্যবহার করুন)।

2020-11-27 19:51 UTC, Aftabuzzaman reviewed
এগুলি সংশোধন করা দরকার।

2020-11-27 19:51 UTC, Aftabuzzaman commented on translations.php
> +      'bn' => 'রেসপন্সিভ',
**প্রতিক্রিয়াশীল** হবে।

2020-11-27 19:51 UTC, Aftabuzzaman commented on translations.php
> +      'bn' => 'সোশ্যাল মিডিয়া',
সামাজিক মাধ্যম লিখুন

2020-11-27 19:51 UTC, Aftabuzzaman commented on translations.php
> +				'যুক্তরাজ্যে একটি নিবন্ধিত দায়বদ্ধ লিমিটেড কোম্পানি এবং ওয়েলস নং: 12323854  <br />' .
```
ইংল্যান্ড ও ওয়েলস কোম্পানি নং 12323854 হিসেবে নিবন্ধিত দায়বদ্ধ লিমিটেড কোম্পানি <br />' .
				'অন্যথায় উল্লেখ না করা হলে, এই সাইটের বিষয়বস্তু ' .
				'<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.bn">এট্রিবিউশন-শেয়ারএলাইক ৪.০ আন্তর্জাতিক (সিসি বাই-এসএ ৪.০)</a>-এর অধীনে লাইসেন্সকৃত।
```

লিখুন

2020-11-27 19:51 UTC, Aftabuzzaman commented on translations.php
> +			'bn' => 'স্ট্যাটাস',
**অবস্থা** লিখুন

2020-11-27 19:51 UTC, Aftabuzzaman commented on translations.php
> +      'bn' => 'Miraheze একটি অলাভজনক সংস্থা, বিনামূল্য সম্প্রদায়-কেন্দ্রিক বিনামূল্য উইকি পরিষেবা দেয়া যেটির মূল উদ্দেশ্য',
Miraheze একটি অলাভজনক সংস্থা, বিনামূল্যে সম্প্রদায়-কেন্দ্রিক উইকি পরিষেবা দেয়া যেটির মূল উদ্দেশ্য

লিখুন

2020-11-27 19:51 UTC, Aftabuzzaman commented on translations.php
> +			'bn' => 'Miraheze উইকিপিডিয়ার <a href="https://www.mediawiki.org">মিডিয়াউইকি</a> সফটওয়্যার দিয়েই পরিচালিত হয়।' .
```
'মিরাহেজ উইকিপিডিয়ার মত একই সফটওয়্যার দ্বারা চালিত, যার নাম <a href="https://www.mediawiki.org">মিডিয়াউইকি!</a> ' .
				'আপনি মিডিয়া আপলোড করা থেকে শুরু করে, ছবি বা ভিডিও আপলোড করা, প্রবন্ধ বা ব্লগ লেখা পর্যন্ত যে কোনও কিছু করতে পারেন। ' .
				'মিডিয়াউইকিতে আপনার অভিজ্ঞতা স্বনির্ধারিত করতে আমাদের ২০০টিরও বেশি এক্সটেনশন এবং ১৫টিরও বেশি আবরণ রয়েছে!',
```

লিখুন।

2020-11-27 19:51 UTC, Aftabuzzaman commented on translations.php
> +			'bn' => 'Miraheze যুক্তরাজ্যে মিরাহেজ লিমিটেড হিসাবে (অলাভজনক প্রতিষ্ঠানের স্বীকৃতিসহ) নিবন্ধিত আছে।' .
নিবন্ধিত আছে।-এর পরিবর্তে কেবল "নিবন্ধিত।" লিখলেই হবে।

2020-11-27 19:51 UTC, Aftabuzzaman commented on translations.php
> +      'bn' => 'গোপনীয়তার নীতিমালা',
কেবল **নীতি** লিখুন

2020-11-27 19:51 UTC, Aftabuzzaman commented on translations.php
> +			'bn' => 'এই ফর্মটি পেপালের মাধ্যমে দান করার জন্য (আপনি ক্রেডিট/ডেবিট কার্ড ব্যবহার করতে পারেন। ' .
একটি **)** বাকি

2020-11-27 21:53 UTC, ahmsaqib commented
> @ahmsaqib আমি না খেয়াল করেই, #48 অনুবাদ করে জমা দিয়েছি। অনুগ্রহ করে অনুবাদ মিলিয়ে নিয়ে সংশোধন করুন (দুই অনুবাদের জন্য যেটি বেশি ভালো লাগে সেটি ব্যবহার করুন)।

আপনার রিভিউ অনুসারে আমি সংশোধন করেছি। আপনি আবার রিভিউ করতে পারেন। অথবা এটিকে বাতিল করার জন্য বলতে পারেন। যদি অনুবাদে সমস্যা থাকে।

2020-11-28 00:19 UTC, Aftabuzzaman commented
@ahmsaqib ধন্যবাদ। আর কিছু চোখে পড়লে বলব।

@developer, good to go now.

2020-11-28 00:58 UTC, Aftabuzzaman commented
সংশোধন দরকার: ১১২ নং লাইনে বাক্যের শেষে দাড়ি দেয়া দরকার। ২৭৮ লাইনে **ব্যবহার** বানান ঠিক করা দরকার (_ব্যহার_ লিখেছেন)।

2020-11-28 01:57 UTC, Universal-Omega requested changes
Add the language to https://github.com/miraheze/landing/blob/d5d2778b88714e46aab5bc8d4f18cd59417056e3/index.php#L96

2020-11-28 02:50 UTC, Aftabuzzaman commented
@Universal-Omega https://github.com/miraheze/landing/pull/49

2020-11-28 02:54 UTC, merged

2020-11-28 03:05 UTC, Aftabuzzaman commented
@Universal-Omega Thank you very much.

one request: There is a spelling mistake (i didn't notice when reviewing translation), please replace ব্যহার with ব্যবহার (line 301). And and the end of line 121 add a । (it's called dari, not english l :D), so it will look like this `উদ্দেশ্য।',`

2020-11-28 03:06 UTC, Universal-Omega commented
> @Universal-Omega Thank you very much.
> 
> one request: There is a spelling mistake (i didn't notice when reviewing translation), please replace ব্যহার with ব্যবহার (line 301). And and the end of line 121 add a । (it's called dari, not english l :D), so it will look like this `উদ্দেশ্য।',`

You're welcome, can you please submit a new PR to fix that mistake?

2020-11-28 03:14 UTC, Aftabuzzaman commented
Thanks. Done.